# for running the app in docker locally, create a file local.toml with a marketplace_project value,
# then build the default dockerfile with:
#    docker build -t doit-easily:latest .
# then build this dockerfile with
#       docker build -t doit-easily-local:latest -f Dockerfile.local .
# then you can run the doit-easily-local image on your machine.
FROM eu.gcr.io/talon-farm2/talon-one/marketplace:v3.6.1

COPY local.toml /config/custom-settings.toml